In [323]:
import numpy as np
import pandas as pd
from datetime import date, timedelta
import gc
import os

In [324]:
dRange = pd.date_range(date(2017,8,1), date(2017,8,15))
print("dRange", dRange[0])
print("dRange", dRange.size)

#for i in range(0, dRange.size):
#    print("dRange each ", dRange[i])

#for(eachDate in dRange):
#    print("eachDate ", eachDate)

rangeDt = pd.date_range(date(2017,8,1) - timedelta(days=3), periods=15, freq='D')
print("range dt ", rangeDt)

dRange 2017-08-01 00:00:00
dRange 15
range dt  DatetimeIndex(['2017-07-29', '2017-07-30', '2017-07-31', '2017-08-01',
               '2017-08-02', '2017-08-03', '2017-08-04', '2017-08-05',
               '2017-08-06', '2017-08-07', '2017-08-08', '2017-08-09',
               '2017-08-10', '2017-08-11', '2017-08-12'],
              dtype='datetime64[ns]', freq='D')

In [325]:
df_train = pd.read_csv(
    '../../../data/favgrocery/trainSmall.csv', usecols=[1, 2, 3, 4, 5],
    converters={'unit_sales': lambda u: np.log1p(
        float(u)) if float(u) > 0 else 0},
    parse_dates=["date"]
)
#drop NA values
df_train = df_train.dropna(axis = 0, how ='any')
#convert one column data type to be bool
df_train = df_train.astype({"onpromotion":'bool'})


df_test = pd.read_csv(
    "../../../data/favgrocery/test.csv", usecols=[0, 1, 2, 3, 4],
    parse_dates=["date"]  # , date_parser=parser
).set_index(
    ['store_nbr', 'item_nbr', 'date']
)
df_test = df_test.dropna(axis = 0, how ='any')
df_test = df_test.astype({"onpromotion":'bool'})

In [326]:
print("df_train ", df_train.shape)
print("df_test shape ", df_test.shape)

print("df_train columns ", df_train.columns)
print("df_train column item_nbr all values ", df_train["item_nbr"].values)

df_train  (1570967, 5)
df_test shape  (3370464, 2)
df_train columns  Index(['date', 'store_nbr', 'item_nbr', 'unit_sales', 'onpromotion'], dtype='object')
df_train column item_nbr all values  [ 103665  105574  105575 ... 2110456 2113914 2116416]

In [327]:
items = pd.read_csv(
    "../../../data/favgrocery/items.csv",
)
print("items origin ", items[:5])
items = items.set_index("item_nbr")
print("items after set_index ", items[:5])

stores = pd.read_csv(
    "../../../data/favgrocery/stores.csv",
)
stores = stores.set_index("store_nbr")

items origin     item_nbr        family  class  perishable
0     96995     GROCERY I   1093           0
1     99197     GROCERY I   1067           0
2    103501      CLEANING   3008           0
3    103520     GROCERY I   1028           0
4    103665  BREAD/BAKERY   2712           1
items after set_index                  family  class  perishable
item_nbr
96995        GROCERY I   1093           0
99197        GROCERY I   1067           0
103501        CLEANING   3008           0
103520       GROCERY I   1028           0
103665    BREAD/BAKERY   2712           1

In [328]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
ftTransformFamily = le.fit_transform(items['family'].values)
print("ftTransformFamily ", ftTransformFamily)
items['family'] = ftTransformFamily

stores['city'] = le.fit_transform(stores['city'].values)
stores['state'] = le.fit_transform(stores['state'].values)
stores['type'] = le.fit_transform(stores['type'].values)
print("city ", stores['city'][:5])

ftTransformFamily  [12 12  7 ... 12  3 22]
city  store_nbr
1    18
2    18
3    18
4    18
5    21
Name: city, dtype: int64

In [329]:
#filter according to criteria on one column 
df_2017 = df_train.loc[df_train["date"]>=pd.datetime(2017,1,1)]
print("df_2017 top5", df_2017[:5])

df_2017 top5         date  store_nbr  item_nbr  unit_sales  onpromotion
0 2017-08-01          1    103665    1.609438        False
1 2017-08-01          1    105574    2.197225        False
2 2017-08-01          1    105575    2.708050        False
3 2017-08-01          1    105693    0.693147        False
4 2017-08-01          1    105737    0.693147        False

In [330]:
indexedDF= df_2017.set_index(["store_nbr", "item_nbr", "date"])
print("indexedDF ", indexedDF[:8])
gotOnpromote = indexedDF[["onpromotion"]]
print("gotOnpromote promote [[\"onpromotion\"]] " , gotOnpromote)

promo_2017_train = gotOnpromote.unstack(level=-1).fillna(False)
print("promo_2017_train top5", promo_2017_train[:5])

indexedDF                                 unit_sales  onpromotion
store_nbr item_nbr date
1         103665   2017-08-01    1.609438        False
          105574   2017-08-01    2.197225        False
          105575   2017-08-01    2.708050        False
          105693   2017-08-01    0.693147        False
          105737   2017-08-01    0.693147        False
          105857   2017-08-01    1.945910        False
          106716   2017-08-01    1.791759        False
          108079   2017-08-01    1.098612        False
gotOnpromote promote [["onpromotion"]]                                 onpromotion
store_nbr item_nbr date
1         103665   2017-08-01        False
          105574   2017-08-01        False
          105575   2017-08-01        False
          105693   2017-08-01        False
          105737   2017-08-01        False
          105857   2017-08-01        False
          106716   2017-08-01        False
          108079   2017-08-01        False
          108696   2017-08-01        False
          108786   2017-08-01        False
          108797   2017-08-01        False
          111223   2017-08-01        False
          112830   2017-08-01        False
          114778   2017-08-01        False
          114790   2017-08-01        False
          114800   2017-08-01        False
          115267   2017-08-01        False
          115611   2017-08-01        False
          115693   2017-08-01        False
          115720   2017-08-01        False
          115850   2017-08-01        False
          115892   2017-08-01        False
          115893   2017-08-01        False
          116017   2017-08-01        False
          116018   2017-08-01        False
          116311   2017-08-01        False
          119024   2017-08-01        False
          119026   2017-08-01        False
          119141   2017-08-01        False
          119187   2017-08-01        False
...                                    ...
54        2056557  2017-08-15        False
          2057442  2017-08-15        False
          2058758  2017-08-15        False
          2059277  2017-08-15        False
          2059342  2017-08-15        False
          2059799  2017-08-15         True
          2060787  2017-08-15         True
          2060793  2017-08-15         True
          2060910  2017-08-15         True
          2061025  2017-08-15         True
          2061033  2017-08-15         True
          2061404  2017-08-15        False
          2062477  2017-08-15        False
          2067056  2017-08-15        False
          2081056  2017-08-15        False
          2081064  2017-08-15        False
          2081095  2017-08-15        False
          2081161  2017-08-15        False
          2084278  2017-08-15        False
          2084557  2017-08-15        False
          2086882  2017-08-15        False
          2087409  2017-08-15        False
          2087978  2017-08-15        False
          2088922  2017-08-15        False
          2089036  2017-08-15        False
          2089339  2017-08-15        False
          2106464  2017-08-15         True
          2110456  2017-08-15        False
          2113914  2017-08-15         True
          2116416  2017-08-15        False

[1570967 rows x 1 columns]
promo_2017_train top5                    onpromotion                                              \
date                2017-08-01 2017-08-02 2017-08-03 2017-08-04 2017-08-05
store_nbr item_nbr
1         96995          False      False      False      False      False
          99197          False      False      False      False      False
          103520         False      False      False      False      False
          103665         False      False      False      False      False
          105574         False      False      False      False      False

                                                                           \
date               2017-08-06 2017-08-07 2017-08-08 2017-08-09 2017-08-10
store_nbr item_nbr
1         96995         False      False      False      False      False
          99197         False      False      False      False      False
          103520        False      False      False      False      False
          103665        False      False      False      False      False
          105574        False      False      False      False      False


date               2017-08-11 2017-08-12 2017-08-13 2017-08-14 2017-08-15
store_nbr item_nbr
1         96995         False      False      False      False      False
          99197         False      False      False      False      False
          103520        False      False      False      False      False
          103665        False      False      False      False      False
          105574        False      False      False      False      False

In [331]:
print("promo_2017_train top5 ", promo_2017_train[:5])
print(" promo_2017_train.columns columns ",  promo_2017_train.columns)
print(" promo_2017_train.columns columns  get_level_values ",  promo_2017_train.columns.get_level_values(1))
promo_2017_train.columns = promo_2017_train.columns.get_level_values(1)
promo_2017_test = df_test[["onpromotion"]].unstack(level=-1).fillna(False)
promo_2017_test.columns = promo_2017_test.columns.get_level_values(1)
promo_2017_test = promo_2017_test.reindex(promo_2017_train.index).fillna(False)
promo_2017 = pd.concat([promo_2017_train, promo_2017_test], axis=1)
del promo_2017_test, promo_2017_train

promo_2017_train top5                     onpromotion                                              \
date                2017-08-01 2017-08-02 2017-08-03 2017-08-04 2017-08-05
store_nbr item_nbr
1         96995          False      False      False      False      False
          99197          False      False      False      False      False
          103520         False      False      False      False      False
          103665         False      False      False      False      False
          105574         False      False      False      False      False

                                                                           \
date               2017-08-06 2017-08-07 2017-08-08 2017-08-09 2017-08-10
store_nbr item_nbr
1         96995         False      False      False      False      False
          99197         False      False      False      False      False
          103520        False      False      False      False      False
          103665        False      False      False      False      False
          105574        False      False      False      False      False


date               2017-08-11 2017-08-12 2017-08-13 2017-08-14 2017-08-15
store_nbr item_nbr
1         96995         False      False      False      False      False
          99197         False      False      False      False      False
          103520        False      False      False      False      False
          103665        False      False      False      False      False
          105574        False      False      False      False      False
 promo_2017_train.columns columns  MultiIndex(levels=[['onpromotion'], [2017-08-01 00:00:00, 2017-08-02 00:00:00, 2017-08-03 00:00:00, 2017-08-04 00:00:00, 2017-08-05 00:00:00, 2017-08-06 00:00:00, 2017-08-07 00:00:00, 2017-08-08 00:00:00, 2017-08-09 00:00:00, 2017-08-10 00:00:00, 2017-08-11 00:00:00, 2017-08-12 00:00:00, 2017-08-13 00:00:00, 2017-08-14 00:00:00, 2017-08-15 00:00:00]],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]],
           names=[None, 'date'])
 promo_2017_train.columns columns  get_level_values  DatetimeIndex(['2017-08-01', '2017-08-02', '2017-08-03', '2017-08-04',
               '2017-08-05', '2017-08-06', '2017-08-07', '2017-08-08',
               '2017-08-09', '2017-08-10', '2017-08-11', '2017-08-12',
               '2017-08-13', '2017-08-14', '2017-08-15'],
              dtype='datetime64[ns]', name='date', freq=None)

In [332]:
df_2017 = df_2017.set_index(
    ["store_nbr", "item_nbr", "date"])[["unit_sales"]].unstack(
        level=-1).fillna(0)
print("df_2017 with unit_Sales ", df_2017[:2])
dfLevelValues1 = df_2017.columns.get_level_values(1)
print("get Level_values", dfLevelValues1)
df_2017.columns = dfLevelValues1
print("df_2017 after set columns: ", df_2017[:2])

df_2017_index_level1 = df_2017.index.get_level_values(1)
print("df_2017 index " , df_2017_index_level1)
items = items.reindex(df_2017_index_level1)
print("items after reindex ", items[:2])

df_2017_index_level0 = df_2017.index.get_level_values(0)
print("df_2017 index " , df_2017_index_level1)
stores = stores.reindex(df_2017_index_level0)
print("stores after reindex ", stores[:2])

df_2017 with unit_Sales                     unit_sales                                              \
date               2017-08-01 2017-08-02 2017-08-03 2017-08-04 2017-08-05
store_nbr item_nbr
1         96995           0.0   0.693147   1.098612        0.0   0.000000
          99197           0.0   0.000000   0.000000        0.0   0.693147

                                                                           \
date               2017-08-06 2017-08-07 2017-08-08 2017-08-09 2017-08-10
store_nbr item_nbr
1         96995      1.098612   1.098612        0.0   0.000000   0.693147
          99197      0.000000   1.098612        0.0   1.098612   0.000000


date               2017-08-11 2017-08-12 2017-08-13 2017-08-14 2017-08-15
store_nbr item_nbr
1         96995           0.0        0.0        0.0        0.0        0.0
          99197           0.0        0.0        0.0        0.0        0.0
get Level_values DatetimeIndex(['2017-08-01', '2017-08-02', '2017-08-03', '2017-08-04',
               '2017-08-05', '2017-08-06', '2017-08-07', '2017-08-08',
               '2017-08-09', '2017-08-10', '2017-08-11', '2017-08-12',
               '2017-08-13', '2017-08-14', '2017-08-15'],
              dtype='datetime64[ns]', name='date', freq=None)
df_2017 after set columns:  date                2017-08-01  2017-08-02  2017-08-03  2017-08-04  \
store_nbr item_nbr
1         96995            0.0    0.693147    1.098612         0.0
          99197            0.0    0.000000    0.000000         0.0

date                2017-08-05  2017-08-06  2017-08-07  2017-08-08  \
store_nbr item_nbr
1         96995       0.000000    1.098612    1.098612         0.0
          99197       0.693147    0.000000    1.098612         0.0

date                2017-08-09  2017-08-10  2017-08-11  2017-08-12  \
store_nbr item_nbr
1         96995       0.000000    0.693147         0.0         0.0
          99197       1.098612    0.000000         0.0         0.0

date                2017-08-13  2017-08-14  2017-08-15
store_nbr item_nbr
1         96995            0.0         0.0         0.0
          99197            0.0         0.0         0.0
df_2017 index  Int64Index([  96995,   99197,  103520,  103665,  105574,  105575,  105577,
             105693,  105737,  105857,
            ...
            2101795, 2103250, 2105347, 2106464, 2108569, 2109909, 2110456,
            2113343, 2113914, 2116416],
           dtype='int64', name='item_nbr', length=146247)
items after reindex            family  class  perishable
item_nbr
96995         12   1093           0
99197         12   1067           0
df_2017 index  Int64Index([  96995,   99197,  103520,  103665,  105574,  105575,  105577,
             105693,  105737,  105857,
            ...
            2101795, 2103250, 2105347, 2106464, 2108569, 2109909, 2110456,
            2113343, 2113914, 2116416],
           dtype='int64', name='item_nbr', length=146247)
stores after reindex             city  state  type  cluster
store_nbr
1            18     12     3       13
1            18     12     3       13

In [333]:
grpByDF2017 = df_2017.groupby('item_nbr')
print("after group by", grpByDF2017)
df_2017_item = grpByDF2017[df_2017.columns].sum()
print("df_2017_item after sum ", df_2017_item[:5])

promo_2017_item = promo_2017.groupby('item_nbr')[promo_2017.columns].sum()
print("promo_2017_item after sum ", promo_2017_item[:5])

df_2017_store_class = df_2017.reset_index()
print("df_2017_store_class after reset_index ", df_2017_store_class[:5])
df_2017_store_class['class'] = items['class'].values
df_2017_store_class_index = df_2017_store_class[['class', 'store_nbr']]
df_2017_store_class = df_2017_store_class.groupby(['class', 'store_nbr'])[df_2017.columns].sum()
print("df_2017_store_class after sum ", df_2017_store_class[:5])

df_2017_promo_store_class = promo_2017.reset_index()
df_2017_promo_store_class['class'] = items['class'].values
df_2017_promo_store_class_index = df_2017_promo_store_class[['class', 'store_nbr']]
df_2017_promo_store_class = df_2017_promo_store_class.groupby(['class', 'store_nbr'])[promo_2017.columns].sum()
print("df_2017_promo_store_class after sum ", df_2017_promo_store_class[:5])

after group by <pandas.core.groupby.DataFrameGroupBy object at 0x7f83f04367f0>
df_2017_item after sum  date      2017-08-01  2017-08-02  2017-08-03  2017-08-04  2017-08-05  \
item_nbr
96995       5.950643    9.821844    9.534161    6.356108    7.336937
99197       5.257495    3.583519    2.079442    1.386294    3.178054
103501     47.547413   41.086834   36.374643   33.346057   40.030669
103520     49.974750   33.589403   43.176097   47.286190   58.097702
103665     42.070645   41.189906   40.528843   47.786240   50.796730

date      2017-08-06  2017-08-07  2017-08-08  2017-08-09  2017-08-10  \
item_nbr
96995       5.662960    7.454720    2.484907    5.950643    5.545177
99197       3.178054    4.969813    3.178054    4.969813    2.079442
103501     38.578235   33.531460   35.296421   35.584104   26.270815
103520     35.630624   32.567752   47.213872   41.198030   43.569852
103665     50.919628   41.262812   34.711732   34.095546   48.162787

date      2017-08-11  2017-08-12  2017-08-13  2017-08-14  2017-08-15
item_nbr
96995       8.841014    7.742402    4.969813    7.167038    7.742402
99197       2.197225    1.386294    2.079442    0.000000    0.000000
103501     32.776619   34.416498   36.546914   34.773173   35.512841
103520     48.697330   47.015385   39.070042   33.798042   40.030669
103665     50.980653   39.807856   39.016553   34.262348   35.741351
promo_2017_item after sum  date      2017-08-01  2017-08-02  2017-08-03  2017-08-04  2017-08-05  \
item_nbr
96995            0.0         0.0         0.0         0.0         0.0
99197            0.0         0.0         0.0         0.0         0.0
103501           0.0         0.0         0.0         0.0         0.0
103520           0.0         0.0         0.0         0.0         0.0
103665           0.0         0.0         0.0         0.0         0.0

date      2017-08-06  2017-08-07  2017-08-08  2017-08-09  2017-08-10  \
item_nbr
96995            0.0         0.0         0.0         0.0         0.0
99197            0.0         0.0         0.0         0.0         0.0
103501           0.0         0.0         0.0         0.0         0.0
103520           0.0         0.0         0.0         0.0         0.0
103665          10.0         0.0         0.0         0.0         0.0

date         ...      2017-08-22  2017-08-23  2017-08-24  2017-08-25  \
item_nbr     ...
96995        ...             0.0         0.0         0.0         0.0
99197        ...             0.0         0.0         0.0         0.0
103501       ...             0.0         0.0         0.0         0.0
103520       ...             0.0         0.0         0.0         0.0
103665       ...             0.0         0.0         0.0         0.0

date      2017-08-26  2017-08-27  2017-08-28  2017-08-29  2017-08-30  \
item_nbr
96995            0.0         0.0         0.0         0.0         1.0
99197            0.0         0.0         0.0         0.0         0.0
103501           0.0         0.0         0.0         0.0         3.0
103520           0.0         0.0         0.0         0.0         1.0
103665           0.0        12.0         0.0         0.0         1.0

date      2017-08-31
item_nbr
96995            0.0
99197            0.0
103501           1.0
103520           1.0
103665           0.0

[5 rows x 31 columns]
df_2017_store_class after reset_index  date  store_nbr  item_nbr  2017-08-01 00:00:00  2017-08-02 00:00:00  \
0             1     96995             0.000000             0.693147
1             1     99197             0.000000             0.000000
2             1    103520             0.000000             0.693147
3             1    103665             1.609438             1.098612
4             1    105574             2.197225             2.197225

date  2017-08-03 00:00:00  2017-08-04 00:00:00  2017-08-05 00:00:00  \
0                1.098612             0.000000             0.000000
1                0.000000             0.000000             0.693147
2                1.098612             1.386294             0.000000
3                1.098612             2.197225             1.386294
4                1.945910             1.791759             2.079442

date  2017-08-06 00:00:00  2017-08-07 00:00:00  2017-08-08 00:00:00  \
0                1.098612             1.098612             0.000000
1                0.000000             1.098612             0.000000
2                0.000000             0.000000             1.386294
3                0.693147             1.098612             0.000000
4                0.000000             1.791759             2.079442

date  2017-08-09 00:00:00  2017-08-10 00:00:00  2017-08-11 00:00:00  \
0                0.000000             0.693147             0.000000
1                1.098612             0.000000             0.000000
2                0.000000             1.386294             0.693147
3                2.079442             2.302585             1.098612
4                1.945910             2.397895             1.791759

date  2017-08-12 00:00:00  2017-08-13 00:00:00  2017-08-14 00:00:00  \
0                0.000000             0.000000             0.000000
1                0.000000             0.000000             0.000000
2                0.693147             0.693147             0.000000
3                0.000000             0.000000             0.693147
4                1.791759             0.000000             1.386294

date  2017-08-15 00:00:00
0                0.000000
1                0.000000
2                0.000000
3                0.693147
4                1.609438
df_2017_store_class after sum  date             2017-08-01  2017-08-02  2017-08-03  2017-08-04  2017-08-05  \
class store_nbr
1002  1           11.836747   13.253813   10.632774   11.164219    8.658693
      2           24.903783   28.164935   24.597752   24.638574   24.579734
      3           35.343941   38.776219   31.232261   32.868679   36.456481
      4           22.184920   20.272296   17.025249   16.348979   17.564246
      5           16.873699   15.407843   11.192390   12.501723   15.132583

date             2017-08-06  2017-08-07  2017-08-08  2017-08-09  2017-08-10  \
class store_nbr
1002  1            6.068426   11.966952   13.458607   11.431281   13.367622
      2           28.459131   25.885741   22.351737   21.326989   16.401095
      3           38.142670   27.082659   30.859413   28.748667   30.232542
      4           26.304582   10.961278   17.278515   13.223041   17.735273
      5           12.647677   13.969433   11.901285   15.333254   13.851650

date             2017-08-11  2017-08-12  2017-08-13  2017-08-14  2017-08-15
class store_nbr
1002  1            5.545177   13.628506    5.375278   18.639141   10.450452
      2           26.828830   27.567914   25.059788   21.576931   24.121024
      3           36.638416   31.272846   32.256757   33.608285   24.929109
      4           19.822911   16.806560   23.187741   16.267563   16.267563
      5           10.332669   14.416963   15.538049   11.192390   11.443704
df_2017_promo_store_class after sum  date             2017-08-01  2017-08-02  2017-08-03  2017-08-04  2017-08-05  \
class store_nbr
1002  1                 1.0         1.0         1.0         1.0         1.0
      2                 3.0         2.0         1.0         0.0         1.0
      3                 0.0         3.0         1.0         1.0         1.0
      4                 2.0         2.0         1.0         1.0         1.0
      5                 3.0         3.0         0.0         0.0         1.0

date             2017-08-06  2017-08-07  2017-08-08  2017-08-09  2017-08-10  \
class store_nbr
1002  1                 1.0         1.0         1.0         1.0         1.0
      2                 1.0         1.0         1.0         1.0         1.0
      3                 1.0         1.0         1.0         1.0         1.0
      4                 1.0         1.0         1.0         1.0         1.0
      5                 1.0         1.0         0.0         1.0         1.0

date                ...      2017-08-22  2017-08-23  2017-08-24  2017-08-25  \
class store_nbr     ...
1002  1             ...             1.0         1.0         1.0         1.0
      2             ...             1.0         1.0         1.0         1.0
      3             ...             1.0         1.0         1.0         1.0
      4             ...             1.0         1.0         1.0         1.0
      5             ...             0.0         1.0         1.0         0.0

date             2017-08-26  2017-08-27  2017-08-28  2017-08-29  2017-08-30  \
class store_nbr
1002  1                 1.0         1.0         1.0         1.0         1.0
      2                 1.0         1.0         1.0         1.0         1.0
      3                 1.0         1.0         1.0         1.0         1.0
      4                 1.0         1.0         1.0         1.0         1.0
      5                 1.0         1.0         1.0         1.0         1.0

date             2017-08-31
class store_nbr
1002  1                 1.0
      2                 1.0
      3                 1.0
      4                 2.0
      5                 0.0

[5 rows x 31 columns]

In [334]:
def get_timespan(df, dt, minus, periods, freq='D'):
    rangeDt = pd.date_range(dt - timedelta(days=minus), periods=periods, freq=freq)
    print("range dt ", rangeDt)
    return df[rangeDt]

def prepare_dataset(df, promo_df, t2017, is_train=True, name_prefix=None):
    print("promo_df", promo_df[:5])
    print("origin t2017 ", t2017)
    print("cal range ", pd.date_range(t2017 - timedelta(days=14), periods=14, freq='D'))
    X = {
        "promo_14_2017": get_timespan(promo_df, t2017, 7, 7).sum(axis=1).values,
        "promo_60_2017": get_timespan(promo_df, t2017, 60, 60).sum(axis=1).values,
        "promo_140_2017": get_timespan(promo_df, t2017, 140, 140).sum(axis=1).values,
        "promo_3_2017_aft": get_timespan(promo_df, t2017 + timedelta(days=16), 15, 3).sum(axis=1).values,
        "promo_7_2017_aft": get_timespan(promo_df, t2017 + timedelta(days=16), 15, 7).sum(axis=1).values,
        "promo_14_2017_aft": get_timespan(promo_df, t2017 + timedelta(days=16), 15, 14).sum(axis=1).values,
    }

    for i in [3, 7, 14, 30, 60, 140]:
        tmp = get_timespan(df, t2017, i, i)
        X['diff_%s_mean' % i] = tmp.diff(axis=1).mean(axis=1).values
        X['mean_%s_decay' % i] = (tmp * np.power(0.9, np.arange(i)[::-1])).sum(axis=1).values
        X['mean_%s' % i] = tmp.mean(axis=1).values
        X['median_%s' % i] = tmp.median(axis=1).values
        X['min_%s' % i] = tmp.min(axis=1).values
        X['max_%s' % i] = tmp.max(axis=1).values
        X['std_%s' % i] = tmp.std(axis=1).values

    for i in [3, 7, 14, 30, 60, 140]:
        tmp = get_timespan(df, t2017 + timedelta(days=-7), i, i)
        X['diff_%s_mean_2' % i] = tmp.diff(axis=1).mean(axis=1).values
        X['mean_%s_decay_2' % i] = (tmp * np.power(0.9, np.arange(i)[::-1])).sum(axis=1).values
        X['mean_%s_2' % i] = tmp.mean(axis=1).values
        X['median_%s_2' % i] = tmp.median(axis=1).values
        X['min_%s_2' % i] = tmp.min(axis=1).values
        X['max_%s_2' % i] = tmp.max(axis=1).values
        X['std_%s_2' % i] = tmp.std(axis=1).values

    for i in [7, 14, 30, 60, 140]:
        tmp = get_timespan(df, t2017, i, i)
        X['has_sales_days_in_last_%s' % i] = (tmp > 0).sum(axis=1).values
        X['last_has_sales_day_in_last_%s' % i] = i - ((tmp > 0) * np.arange(i)).max(axis=1).values
        X['first_has_sales_day_in_last_%s' % i] = ((tmp > 0) * np.arange(i, 0, -1)).max(axis=1).values

        tmp = get_timespan(promo_df, t2017, i, i)
        X['has_promo_days_in_last_%s' % i] = (tmp > 0).sum(axis=1).values
        X['last_has_promo_day_in_last_%s' % i] = i - ((tmp > 0) * np.arange(i)).max(axis=1).values
        X['first_has_promo_day_in_last_%s' % i] = ((tmp > 0) * np.arange(i, 0, -1)).max(axis=1).values

    tmp = get_timespan(promo_df, t2017 + timedelta(days=16), 15, 15)
    X['has_promo_days_in_after_15_days'] = (tmp > 0).sum(axis=1).values
    X['last_has_promo_day_in_after_15_days'] = i - ((tmp > 0) * np.arange(15)).max(axis=1).values
    X['first_has_promo_day_in_after_15_days'] = ((tmp > 0) * np.arange(15, 0, -1)).max(axis=1).values

    for i in range(1, 16):
        X['day_%s_2017' % i] = get_timespan(df, t2017, i, 1).values.ravel()

    for i in range(7):
        X['mean_4_dow{}_2017'.format(i)] = get_timespan(df, t2017, 28-i, 4, freq='7D').mean(axis=1).values
        X['mean_20_dow{}_2017'.format(i)] = get_timespan(df, t2017, 140-i, 20, freq='7D').mean(axis=1).values

    for i in range(-16, 16):
        X["promo_{}".format(i)] = promo_df[t2017 + timedelta(days=i)].values.astype(np.uint8)

    X = pd.DataFrame(X)

    if is_train:
        y = df[
            pd.date_range(t2017, periods=16)
        ].values
        return X, y
    if name_prefix is not None:
        X.columns = ['%s_%s' % (name_prefix, c) for c in X.columns]
    return X 

t2017 = date(2017, 8, 15)
delta = timedelta(days=1 * 2)
print("delta ", delta)
#X_tmp, y_tmp = prepare_dataset(df_2017, promo_2017, t2017 + delta)
print("promo_2017 " , promo_2017[:3])
promo_14_2017 = get_timespan(promo_2017, t2017, 7, 7)
print("promo_14_2017 " , promo_14_2017)

#sum according to row.
promo_14_2017Sum = promo_14_2017.sum(axis=1)
print("promo_14_2017Sum " , promo_14_2017Sum)


promo_14_2017SumValues = promo_14_2017Sum.values
print("promo_14_2017SumValues " , promo_14_2017SumValues)

delta  2 days, 0:00:00
promo_2017  date                2017-08-01  2017-08-02  2017-08-03  2017-08-04  \
store_nbr item_nbr
1         96995          False       False       False       False
          99197          False       False       False       False
          103520         False       False       False       False

date                2017-08-05  2017-08-06  2017-08-07  2017-08-08  \
store_nbr item_nbr
1         96995          False       False       False       False
          99197          False       False       False       False
          103520         False       False       False       False

date                2017-08-09  2017-08-10     ...      2017-08-22  \
store_nbr item_nbr                             ...
1         96995          False       False     ...           False
          99197          False       False     ...           False
          103520         False       False     ...           False

date                2017-08-23  2017-08-24  2017-08-25  2017-08-26  \
store_nbr item_nbr
1         96995          False       False       False       False
          99197          False       False       False       False
          103520         False       False       False       False

date                2017-08-27  2017-08-28  2017-08-29  2017-08-30  2017-08-31
store_nbr item_nbr
1         96995          False       False       False       False       False
          99197          False       False       False       False       False
          103520         False       False       False       False       False

[3 rows x 31 columns]
range dt  DatetimeIndex(['2017-08-08', '2017-08-09', '2017-08-10', '2017-08-11',
               '2017-08-12', '2017-08-13', '2017-08-14'],
              dtype='datetime64[ns]', freq='D')
promo_14_2017  date                2017-08-08  2017-08-09  2017-08-10  2017-08-11  \
store_nbr item_nbr
1         96995          False       False       False       False
          99197          False       False       False       False
          103520         False       False       False       False
          103665         False       False       False       False
          105574         False       False       False       False
          105575         False       False       False       False
          105577         False        True       False       False
          105693         False       False       False       False
          105737         False       False       False       False
          105857         False       False       False       False
          106716         False       False       False       False
          108079         False       False       False       False
          108696         False       False       False        True
          108698         False       False       False       False
          108701         False        True        True        True
          108786         False       False       False       False
          108797          True        True        True        True
          108862         False       False       False       False
          108952         False       False       False       False
          111223         False       False       False       False
          111397         False       False       False       False
          112830         False       False       False       False
          114778         False       False       False       False
          114790          True        True        True        True
          114799         False       False       False       False
          114800         False       False       False       False
          115267         False       False       False       False
          115611         False       False       False       False
          115693         False       False       False       False
          115720         False       False       False       False
...                        ...         ...         ...         ...
54        2072545        False       False       False       False
          2081056        False       False       False       False
          2081064        False       False       False       False
          2081095        False       False       False       False
          2081142        False       False       False       False
          2081161        False       False       False       False
          2083837        False        True        True       False
          2083859        False        True       False       False
          2084278        False       False       False       False
          2084557        False       False       False       False
          2086882        False        True       False       False
          2087374        False       False       False       False
          2087409        False       False       False       False
          2087543        False       False       False       False
          2087567        False       False       False       False
          2087978        False       False       False       False
          2088922        False       False       False       False
          2089036        False       False       False       False
          2089339        False       False       False       False
          2099230        False       False       False       False
          2101795        False       False       False       False
          2103250        False       False       False       False
          2105347        False       False       False       False
          2106464        False       False       False       False
          2108569        False       False       False       False
          2109909        False       False       False       False
          2110456        False       False       False       False
          2113343        False       False       False       False
          2113914         True        True        True       False
          2116416        False       False       False       False

date                2017-08-12  2017-08-13  2017-08-14
store_nbr item_nbr
1         96995          False       False       False
          99197          False       False       False
          103520         False       False       False
          103665         False       False       False
          105574         False       False       False
          105575         False       False       False
          105577         False       False       False
          105693         False       False       False
          105737         False       False       False
          105857         False       False       False
          106716         False       False       False
          108079         False       False       False
          108696         False       False       False
          108698         False       False       False
          108701         False        True        True
          108786         False       False       False
          108797          True        True        True
          108862         False       False       False
          108952         False       False       False
          111223         False       False       False
          111397         False       False       False
          112830         False       False       False
          114778         False       False       False
          114790          True        True       False
          114799         False       False       False
          114800         False       False       False
          115267         False       False       False
          115611         False       False       False
          115693         False       False       False
          115720         False       False       False
...                        ...         ...         ...
54        2072545        False       False       False
          2081056        False       False       False
          2081064        False       False       False
          2081095        False       False       False
          2081142        False       False       False
          2081161        False       False       False
          2083837        False        True       False
          2083859        False       False       False
          2084278        False       False       False
          2084557        False       False       False
          2086882        False       False       False
          2087374        False       False       False
          2087409        False       False       False
          2087543        False       False       False
          2087567        False       False       False
          2087978        False       False       False
          2088922        False       False       False
          2089036        False       False       False
          2089339        False       False       False
          2099230        False       False       False
          2101795        False       False       False
          2103250        False       False       False
          2105347        False       False       False
          2106464        False       False        True
          2108569        False       False       False
          2109909        False       False       False
          2110456        False       False       False
          2113343        False       False       False
          2113914        False        True        True
          2116416        False       False       False

[146247 rows x 7 columns]
promo_14_2017Sum  store_nbr  item_nbr
1          96995       0
           99197       0
           103520      0
           103665      0
           105574      0
           105575      0
           105577      1
           105693      0
           105737      0
           105857      0
           106716      0
           108079      0
           108696      1
           108698      0
           108701      5
           108786      0
           108797      7
           108862      0
           108952      0
           111223      0
           111397      0
           112830      0
           114778      0
           114790      6
           114799      0
           114800      0
           115267      0
           115611      0
           115693      0
           115720      0
                      ..
54         2072545     0
           2081056     0
           2081064     0
           2081095     0
           2081142     0
           2081161     0
           2083837     3
           2083859     1
           2084278     0
           2084557     0
           2086882     1
           2087374     0
           2087409     0
           2087543     0
           2087567     0
           2087978     0
           2088922     0
           2089036     0
           2089339     0
           2099230     0
           2101795     0
           2103250     0
           2105347     0
           2106464     1
           2108569     0
           2109909     0
           2110456     0
           2113343     0
           2113914     5
           2116416     0
Length: 146247, dtype: int64
promo_14_2017SumValues  [0 0 0 ... 0 5 0]

In [335]:
#last 3 days data 
df_2017_last3d = get_timespan(df_2017, t2017, 3, 3)
print("last 3 days df ", df_2017_last3d[:5])

#Difference with previous column
print("last 3 days df diff ", df_2017_last3d.diff(axis=1)[:5])
#mean: average 
print("last 3 days df diff mean ", df_2017_last3d.diff(axis=1).mean(axis=1)[:5])
X= {}
X['diff_3_mean'] = df_2017_last3d.diff(axis=1).mean(axis=1).values

tmp = df_2017_last3d
print("tmp>0", (tmp>0)[:5])

print("tmp>0 * np.arrange(3)", (tmp > 0) * np.arange(3)[:5])

X['has_sales_days_in_last_3'] = (tmp > 0).sum(axis=1).values
print("has_sales_days_in_last_3 " , (tmp > 0).sum(axis=1).values)
X['last_has_sales_day_in_last_3'] = i - ((tmp > 0) * np.arange(3)).max(axis=1).values
print("last_has_sales_day_in_last_3 " , X['last_has_sales_day_in_last_3'])

X['first_has_sales_day_in_last_3'] = ((tmp > 0) * np.arange(3, 0, -1)).max(axis=1).values
print("first_has_sales_day_in_last_3 " , X['first_has_sales_day_in_last_3'])

range dt  DatetimeIndex(['2017-08-12', '2017-08-13', '2017-08-14'], dtype='datetime64[ns]', freq='D')
last 3 days df  date                2017-08-12  2017-08-13  2017-08-14
store_nbr item_nbr
1         96995       0.000000    0.000000    0.000000
          99197       0.000000    0.000000    0.000000
          103520      0.693147    0.693147    0.000000
          103665      0.000000    0.000000    0.693147
          105574      1.791759    0.000000    1.386294
last 3 days df diff  date                2017-08-12  2017-08-13  2017-08-14
store_nbr item_nbr
1         96995            NaN    0.000000    0.000000
          99197            NaN    0.000000    0.000000
          103520           NaN    0.000000   -0.693147
          103665           NaN    0.000000    0.693147
          105574           NaN   -1.791759    1.386294
last 3 days df diff mean  store_nbr  item_nbr
1          96995       0.000000
           99197       0.000000
           103520     -0.346574
           103665      0.346574
           105574     -0.202733
dtype: float64
tmp>0 date                2017-08-12  2017-08-13  2017-08-14
store_nbr item_nbr
1         96995          False       False       False
          99197          False       False       False
          103520          True        True       False
          103665         False       False        True
          105574          True       False        True
tmp>0 * np.arrange(3) date               2017-08-12 2017-08-13 2017-08-14
store_nbr item_nbr
1         96995             0          0          0
          99197             0          0          0
          103520            0          1          0
          103665            0          0          2
          105574            0          0          2
          105575            0          1          2
          105577            0          0          2
          105693            0          1          2
          105737            0          0          2
          105857            0          1          2
          106716            0          1          2
          108079            0          0          0
          108696            0          0          2
          108698            0          1          2
          108701            0          1          2
          108786            0          1          2
          108797            0          1          2
          108862            0          1          2
          108952            0          1          2
          111223            0          1          2
          111397            0          0          0
          112830            0          0          2
          114778            0          0          2
          114790            0          1          0
          114799            0          1          0
          114800            0          0          2
          115267            0          1          0
          115611            0          1          2
          115693            0          0          2
          115720            0          0          0
...                       ...        ...        ...
54        2072545           0          0          2
          2081056           0          1          2
          2081064           0          1          2
          2081095           0          1          2
          2081142           0          0          2
          2081161           0          1          2
          2083837           0          1          0
          2083859           0          1          2
          2084278           0          1          2
          2084557           0          1          2
          2086882           0          1          2
          2087374           0          0          2
          2087409           0          0          2
          2087543           0          0          0
          2087567           0          0          0
          2087978           0          1          2
          2088922           0          1          2
          2089036           0          1          2
          2089339           0          1          2
          2099230           0          0          0
          2101795           0          0          0
          2103250           0          0          0
          2105347           0          0          0
          2106464           0          0          2
          2108569           0          0          2
          2109909           0          1          2
          2110456           0          0          2
          2113343           0          0          2
          2113914           0          1          2
          2116416           0          1          2

[146247 rows x 3 columns]
has_sales_days_in_last_3  [0 0 2 ... 1 2 3]
last_has_sales_day_in_last_3  [14. 14. 13. ... 12. 12. 12.]
first_has_sales_day_in_last_3  [0. 0. 3. ... 1. 2. 3.]